# Generated by Django 4.2.6 on 2023-12-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_recipe_author_recipe_created_at_recipe_img_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='main_ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='sub_ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
