# Generated by Django 4.0.5 on 2023-12-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_recipe_ingredient_recipe_main_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='classification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='n_main_ingredients',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='n_sub_ingredients',
            field=models.IntegerField(null=True),
        ),
    ]
