# Generated by Django 4.2.6 on 2023-12-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author',
            new_name='author_id',
        ),
    ]
