# Generated by Django 4.0.5 on 2023-12-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author_id',
            new_name='author',
        ),
    ]
